apiVersion: apps/v1
kind: Deployment
metadata:
  name: tgndevs-demoapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tgndevs-demoapp
  template:
    metadata:
      labels:
        app: tgndevs-demoapp
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.8
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: I just deployed this on Kubernetes!