---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: demoapp
  namespace: tgndevs
spec:
  imageRepositoryRef:
    name: demoapp
  policy:
    semver:
      range: '=1.9.2'
