name: CI Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          no-cache: true
          tags: tgndevs/demoapp:latest
          file: Dockerfile
          context: app
          build-args: |
            IMAGE_VERSION=1.9
            IMAGE_SOURCE_REVISION=$GITHUB_SHA

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}