name: Update Flux components

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update-flux:
    runs-on: ubuntu-latest

    env:
      CLUSTER_NAME: GitopsAks

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main

      - name: Check for updates
        id: update
        run: |
          flux install \
            --export > ./clusters/${CLUSTER_NAME}/flux-system/gotk-components.yaml

          VERSION="$(flux -v)"
          echo "::set-output name=flux_version::$VERSION"
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            branch: update-flux
            commit-message: Update to ${{ steps.update.outputs.flux_version }}
            title: Update to ${{ steps.update.outputs.flux_version }}
            body: |
              ${{ steps.update.outputs.flux_version }}